language: java

sudo: false

addons:
  sonarcloud:
    organization: "doublesunrus-github"
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script: 
- mvn clean test verify -f build/pom.xml -s build/settings.xml 
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f build/pom.xml -s build/settings.xml -Dsonar.projectKey=DoublesunRUS_ru.capralow.dt.conversion

language: node_js
after_success:
- find repository/target/repository/ -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://$FTP_ADDRESS/{} \;

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
