language: java

sudo: false

addons:
  sonarcloud:
    organization: "doublesunrus-github"
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script: 
- mvn clean test verify -f build/pom.xml -s build/settings.xml 
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f build/pom.xml -s build/settings.xml -Dsonar.projectKey=DoublesunRUS_ru.capralow.dt.conversion

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

language: node_js

env:
  - PLUGIN_VERSION="1.0.0"

after_success:
- curl -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_ADDRESS/ -X 'rmdir -r $PLUGIN_VERSION'
- find repository/target/repository/ -type f -execdir curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://$FTP_ADDRESS/$PLUGIN_VERSION/{} \;
