language: java

addons:
  sonarcloud:
    organization: "doublesunrus-github"
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script: mvn test verify -f build/pom.xml -s build/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
